include:
  - project: 'verituity/devops/cicd-templates'
    file: '/infra/terraform-matrix.yml'
    ref: v0.4-stable

variables:
  TF_CLI_VERSION: '1.3.5'
  GITLAB_TOKEN: $TERRAFORM_GITLAB_TOKEN

# -----------------------------------------------------------------------------
#  PLAN STAGE
# -----------------------------------------------------------------------------
plan:
  extends: .tf_plan
  parallel:
    matrix:
      - TF_VARS_FILE: mgt-nonprod
        TF_WORKSPACE: $TF_VARS_FILE
        TF_AZ_BACKEND: $az_backend_management_nonprod
        TF_VAR_az_sub_id: $ARM_SUBSCRIPTION_ID_CAF_MANAGEMENT

# -----------------------------------------------------------------------------
#  APPLY STAGE
# -----------------------------------------------------------------------------
apply:
  extends: .tf_apply
  parallel:
    matrix:
      - TF_VARS_FILE: mgt-nonprod
        TF_WORKSPACE: $TF_VARS_FILE
        TF_AZ_BACKEND: $az_backend_management_nonprod
        TF_VAR_az_sub_id: $ARM_SUBSCRIPTION_ID_CAF_MANAGEMENT
