include:
  - project: 'verituity/devops/cicd-templates'
    file: '/infra/terraform-matrix.yml'
    # ref: v0.4-stable
    ref: feature/use-vars-filename-as-backend

variables:
  TF_CLI_VERSION: '1.3.5'
  GITLAB_TOKEN: $TERRAFORM_GITLAB_TOKEN

plan:
  extends: .tf_plan
  parallel:
    matrix:
      - TF_VARS_FILE: nonprod
        TF_VAR_az_sub_id: $ARM_SUBSCRIPTION_ID_VTY_NONPROD

apply:
  extends: .tf_apply
  parallel:
    matrix:
      - TF_VARS_FILE: nonprod
        TF_VAR_az_sub_id: $ARM_SUBSCRIPTION_ID_VTY_NONPROD
