output "lb_identity_id" {
  value = module.iam.lb_identity_id
}

output "vm_identity_id" {
  value = module.iam.vm_identity_id
}

output "vm_identity_client_id" {
  value = module.iam.vm_identity_client_id
}

output "key_vault_id" {
  description = "Key Vault ID"
  value       = module.keyvault.key_vault_id
}

output "akv_secret_id_vault_server_cert" {
  description = "Secret ID of AKV Certificate for Vault nodes"
  value       = module.keyvault.akv_secret_id_vault_server_cert
}

output "akv_secret_id_vault_vm_tls" {
  description = "Secret ID of AKV secret for Vault Cluster nodes TLS certificate"
  value       = module.keyvault.akv_secret_id_vault_vm_tls
}

output "keyvault_name" {
  description = "Name of the keyvault - autogenerated if one is not specified."
  value       = module.keyvault.keyvault_name
}

output "root_ca_pem" {
  value = module.tls.root_ca_pem
}

output "akv_secret_id_root_ca_pem" {
  description = "Secret ID of AKV secret for private root CA certificate"
  value       = module.keyvault.akv_secret_id_root_ca_pem
}

output "shared_san" {
  value = module.tls.root_ca_pem
}

output "vault_server_cert_pfx" {
  value = module.tls.root_ca_pem
}

output "resource_group" {
  description = "The resource group that was created for Vault cluster resources"
  value       = azurerm_resource_group.vault
}